name: NodeJS with Webpack

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Configure GitHub Pages
        uses: actions/configure-pages@v3
        id: pages

      - name: Use Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: 18.x

      - name: Overwrite .env file
        run: |
          echo "HOST_PATH=${{ steps.pages.outputs.base_url }}" > .env

      - name: Build
        run: |
          npm install
          npm run build:all

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: 'app'

  deploy:
    permissions:
      contents: read
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest

    needs: build

    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
